finished implementing user functionality to create new lists
dmachineni/MetaUniversity_Capstone pull request #5
Opened 2022-07-27 23:20 UTC by dmachineni

2022-07-28 05:20 UTC, DanielCKennedy commented on ui/src/components/App/App.jsx
> +    console.log('handleListDetails function',cat,subCat)
remove console.logs

2022-07-28 05:22 UTC, DanielCKennedy requested changes
Looks good overall! Just remove your log statements

2022-07-28 17:03 UTC, ksio2124fb reviewed
node_modules should not be in source control

2022-07-28 17:04 UTC, ksio2124fb commented
great progress!!

2022-07-28 19:09 UTC, DanielCKennedy commented
> node_modules should not be in source control

Good call out, you may need to modify your .gitignore

2022-07-29 19:54 UTC, DanielCKennedy approved these changes

2022-07-29 20:03 UTC, ksio2124fb approved these changes

2022-07-29 22:37 UTC, merged